name: test
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    # write permission needed to upload the wasm to ghcr
    # Write permission must be also added via Package settings -> Manage Actions access
    permissions:
      packages: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: "Cache generated .wasm file"
        uses: actions/cache@v3
        with:
          path: |
            build/
          key: wasm-module-build-${{ github.sha }}

      - name: "Build wasm module"
        shell: bash
        run: make build-wasm-plugin extract-wasm-plugin

  e2e-local-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install func-e"
        shell: bash
        run: curl https://func-e.io/install.sh | bash -s -- -b /usr/local/bin

      - name: "Restore the wasm files cache"
        uses: actions/cache@v3
        with:
          path: |
            build/
          key: wasm-module-build-${{ github.sha }}

      - name: "Spin up envoy"
        shell: bash
        run: |
          func-e run -c envoy-config.yaml --log-level info --component-log-level wasm:debug &

      - name: "Run local tests"
        env:
          HEALTH_URL: "http://localhost:8001"
          REQ_UNFILTERED: "http://localhost:8001/home"
          REQ_FILTERED: "http://localhost:8001/admin"
        shell: bash
        run: |
          ./tests.sh

  # e2e-istio-tests are based on deploying the WASM module inside a Kind cluster with Istio installed
  # and test it in front of a nginx dummy application.
  e2e-istio-test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    needs: build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: false

      - name: Install Kind
        shell: bash
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.12.0/kind-linux-amd64
          sudo mv ./kind /usr/bin/kind

      - name: Install istioctl
        shell: bash
        run: |
          curl -sL https://istio.io/downloadIstioctl | sh -

      - name: Create Kind cluster
        # kubectl is already installed on the Github Ubuntu worker
        run: |
          kind create cluster --config=./kind-istio/kind-config.yaml
          kubectl scale deployment --replicas 1 coredns --namespace kube-system

      - name: Load local image
        run: kind load docker-image jcchavezs/modsecurity-filter:latest

      - name: Install Istio
        # install istio default (no egress)
        # adds label to inject the sidecars inside default ns
        run: |
          yes | $HOME/.istioctl/bin/istioctl install --set profile=default
          kubectl label namespace default istio-injection=enabled --overwrite

      # metallb will provide an EXTERNAL_IP (taken from metallb-configmap) to the ingress gateway
      - name: Install metallb
        run: |
          kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/namespace.yaml
          kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml
          kubectl apply -f ./kind-istio/metallb-configmap.yaml

      - name: Deploy nginx and Gateway
        run: |
          kubectl apply -f ./kind-istio/workload/deploy-nginx.yaml
          kubectl apply -f ./kind-istio/workload/istio-gateway.yaml

      - name: Deploy WASM-WAF
        run: kubectl apply -f kind-istio/workload/deploy-waf.yaml

      - name: "Run WAF on istio tests"
        # the IP is the one provided by metallb, for more flexibility it may be retrieved via:
        # echo $(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}
        env:
          HEALTH_URL: "http://172.18.0.100/nginx"
          REQ_UNFILTERED: "http://172.18.0.100/nginx"
          REQ_FILTERED: "http://172.18.0.100/admin"
        shell: bash
        run: |
          ./warmup-tests.sh
          ./tests.sh

  publish:
    if: ${{ github.event_name == 'push' && github.event.pull_request.head.repo.full_name == 'jcchavezs/modsecurity-wasm-filter-e2e' }}
    runs-on: ubuntu-latest
    needs: e2e-local-test
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: false

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Push WASM plugin"
        shell: bash
        run: make push-wasm-plugin
